<a href="https://colab.research.google.com/github/R1sh11172/PyTorch_Deep_Proj/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamental

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as py
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]
MATRIX[1]
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TENSOR
TENSOR = torch.tensor([[[7, 1],
                      [5, 4],
                      [2, 5]]])
TENSOR
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because many neural networks learn by using tensors full of random numbers and then adjust those random numbers to better the data representation

`Process: start with random #s -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [12]:
# Create rando tensor of size (3, 4)
random_tensor = torch.rand(2, 3, 5)
random_tensor

tensor([[[0.2910, 0.2310, 0.2128, 0.5952, 0.5614],
         [0.6440, 0.2277, 0.4470, 0.7764, 0.6971],
         [0.8552, 0.5178, 0.0565, 0.5042, 0.6630]],

        [[0.0035, 0.4814, 0.0524, 0.4206, 0.2200],
         [0.3421, 0.2899, 0.1705, 0.7312, 0.1025],
         [0.5124, 0.4202, 0.8601, 0.2954, 0.1898]]])

In [13]:
# Create random tensor thats similar shape to image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [14]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros
# alternatively you can do zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))

ones.dtype

torch.float32

In [16]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [17]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1) # finishes at end-1

In [18]:
ten_zeros = torch.ones_like(input=one_to_ten) #replicates the tensor size with new values
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatye
2. Tensors not on right shape
3. Tensors not on right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [19]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [20]:
float_16_tensor = float_32_tensor.type(torch.float16)
#float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
#                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
float_16_tensor * float_32_tensor


tensor([ 9., 36., 81.])

### Getting information from tensors

1. To get datatype, use tensor.dtype
2. To get shape, use tensor.shape
3. TO get device, use tensor.device

In [22]:
# Create a tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.2572, 0.2970, 0.5588, 0.3927],
        [0.9380, 0.1405, 0.4433, 0.2689],
        [0.8484, 0.1138, 0.1697, 0.0168]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [23]:
# Tensor Operations
tensor = torch.tensor([1, 2, 3])
tensor + 10 # tensor([11, 12, 13])
tensor * 10 # tensor([10, 20, 30])
tensor - 10 # tensor([-9, -8, -7])
torch.mul(tensor, 10) # does same thing as multiplication operator, also has torch.add

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of perforing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot-product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. Inner dimmension must match
2. Resulting matrix has shape of **outer dimensions**

In [24]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [25]:
#Matrix Multiplication
torch.matmul(tensor, tensor) # or @ can be used

tensor(14)

In [26]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [27]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.24 ms, sys: 37 µs, total: 2.28 ms
Wall time: 3.8 ms


In [28]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 111 µs, sys: 0 ns, total: 111 µs
Wall time: 118 µs


tensor(14)

### Common error in DL: Shape Errors

In [29]:
# Shapes for matrix mult
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#torch.matmul(tensor_A, tensor_B) Error - inner dimensions won't match

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using

A **transpose** switches axes or dimensions of given tensors, rows become cols

In [30]:
tensor_B.T, tensor_B.T.shape

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T) # this will work
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [31]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [33]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # examine the error, tensor fo float32 is required to work for torch.mean()

(tensor(45.), tensor(45.))

In [34]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [35]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Find position in tensor that has the minimum value with argmin() -> return index position of target tensor where min is
x.argmin()

tensor(0)

In [37]:
x[0] #indexing and accessing in tensors

tensor(0)

In [38]:
#Position in tensor with max value
x.argmax()

tensor(9)

In [39]:
x[9]

tensor(90)

## Reshaping, staacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to target tensor
* Permute - Return a view of input w/ dimensions permuted(swapped) in a certain way

In [40]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [41]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9) # all we are doing is adding an another dimension, (9, 1) will flip it
# You can change it to be anything as long as it has the same size, for example, x.reshape(3, 4) will change it to a 3x4 matrix if there are 12 elements
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [42]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
# Changing z changes x (because a view of a tensor shares same memory as original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # Vstack is for dim = 0, Hstack is dim = 1
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [45]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dmensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [46]:
#torch.unsqueeze() - adds a single dim to target tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [47]:
# torch.permute - rearranges the dimension of target tensor in specific order
x_original = torch.rand(size=(224, 224, 3)) #height, width, color_channels

# Permute original tensor to rearrange axis (or dim)
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [48]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [49]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
x[0] # first bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
x[0][0] # index on middle bracet

tensor([1, 2, 3])

In [52]:
x[0][0][0] # index most inner bracket - last dim

tensor(1)

In [53]:
# You can alo use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [54]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [55]:
x[:, 1, 1]

tensor([5])

In [56]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index x to return 9
x[0][2][2]

# Index x to return 3, 6, 9
x[:, :, 2]

## PyTorch tensors & NumPy

NumPY is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [58]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning, when converting from numpy, numpy default is float64, must specify otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [59]:
# Change the value of array, what happens to tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # default type is going to be float32
tensor, numpy_tensor

In [ ]:
# Change tensor, what happens to numpy tensor?
tensor = tensor + 1
tensor, numpy_tensor

## Reproductibility (trying to take random out of random)

Neural networks learns by starting with random numbers, doing tensor operations, update random numbers to better represent data over and over again

To reduce randomness in neural networks and PyTorch comes idea of **random seed**.

Reference: https://pytorch.org/docs/stable/notes/randomness.html
Reference: https://en.wikipedia.org/wiki/Random_seed

In [61]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8596, 0.1744, 0.3411, 0.5701],
        [0.8548, 0.1018, 0.6061, 0.5896],
        [0.5687, 0.4118, 0.2593, 0.3528]])
tensor([[0.6077, 0.5908, 0.1172, 0.1411],
        [0.0053, 0.2342, 0.4328, 0.7842],
        [0.6980, 0.1539, 0.8811, 0.2533]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [62]:
# Random and reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 30
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[0.9007, 0.7464, 0.4716, 0.8738],
        [0.7403, 0.7840, 0.8946, 0.6238],
        [0.4276, 0.8421, 0.7454, 0.6181]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
